title: iWriteHere
description: Happy blogging... ❤

# Email and twitter are optional:
# youtube_username: UCjZ09Tf8WvvsYoHmDZWsWBQ
twitter_username: rahulbakshee
github_username: rahulbakshee
linkedin_username: rahulbakshee

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: UA-180649952-1

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
